name: Deploy to IPFS signal

on:
  push:
    branches:
      - "master"

jobs:
  zip-files:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "16.11.0"
          registry-url: "https://registry.npmjs.org"
      - run: yarn
      - name: Build
        run: yarn build
      - name: Edgeserver Upload
        uses: lvkdotsh/edgeserver-action@v0.0.31
        with:
          app_id: '60377749054820352'
          server: https://signal.lvksh.cloud
          token: ${{ secrets.SIGNAL_TOKEN }}
          directory: dist
